import '../models/product.dart';

class ProductService {
  // Simulated product data - In a real app, this would fetch from an API
  Future<List<Product>> getProducts() async {
    await Future.delayed(const Duration(milliseconds: 500));
    
    return [
      Product(
        id: '1',
        name: 'Wireless Bluetooth Headphones',
        description: 'Premium noise-cancelling headphones with 30-hour battery life and superior sound quality.',
        price: 129.99,
        originalPrice: 199.99,
        imageUrl: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=500',
        images: [
          'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=500',
          'https://images.unsplash.com/photo-1484704849700-f032a568e944?w=500',
        ],
        category: 'Electronics',
        rating: 4.5,
        reviewCount: 1234,
        inStock: true,
        brand: 'SoundMax',
        specifications: {
          'Battery Life': '30 hours',
          'Connectivity': 'Bluetooth 5.0',
          'Weight': '250g',
        },
      ),
      Product(
        id: '2',
        name: 'Smart Fitness Watch',
        description: 'Track your health with heart rate monitoring, GPS, and 50+ workout modes.',
        price: 249.99,
        originalPrice: 299.99,
        imageUrl: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=500',
        images: [
          'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=500',
        ],
        category: 'Electronics',
        rating: 4.7,
        reviewCount: 856,
        inStock: true,
        brand: 'FitTech',
        specifications: {
          'Display': '1.4" AMOLED',
          'Battery': '7 days',
          'Water Resistance': '5 ATM',
        },
      ),
      Product(
        id: '3',
        name: 'Organic Cotton T-Shirt',
        description: 'Comfortable and sustainable organic cotton t-shirt in various colors.',
        price: 24.99,
        originalPrice: 34.99,
        imageUrl: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=500',
        images: [
          'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=500',
        ],
        category: 'Fashion',
        rating: 4.3,
        reviewCount: 567,
        inStock: true,
        brand: 'EcoWear',
        specifications: {
          'Material': '100% Organic Cotton',
          'Care': 'Machine Wash',
          'Fit': 'Regular',
        },
      ),
      Product(
        id: '4',
        name: 'Stainless Steel Water Bottle',
        description: 'Insulated water bottle that keeps drinks cold for 24 hours or hot for 12 hours.',
        price: 29.99,
        originalPrice: 39.99,
        imageUrl: 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=500',
        images: [
          'https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=500',
        ],
        category: 'Home & Kitchen',
        rating: 4.6,
        reviewCount: 892,
        inStock: true,
        brand: 'HydroLife',
        specifications: {
          'Capacity': '750ml',
          'Material': 'Stainless Steel',
          'Insulation': 'Double Wall',
        },
      ),
      Product(
        id: '5',
        name: 'Wireless Charging Pad',
        description: 'Fast wireless charging pad compatible with all Qi-enabled devices.',
        price: 19.99,
        originalPrice: 29.99,
        imageUrl: 'https://images.unsplash.com/photo-1586953208448-b95a79798f07?w=500',
        images: [
          'https://images.unsplash.com/photo-1586953208448-b95a79798f07?w=500',
        ],
        category: 'Electronics',
        rating: 4.4,
        reviewCount: 445,
        inStock: true,
        brand: 'ChargePro',
        specifications: {
          'Output': '15W',
          'Compatibility': 'Qi-enabled',
          'LED Indicator': 'Yes',
        },
      ),
      Product(
        id: '6',
        name: 'Leather Backpack',
        description: 'Premium genuine leather backpack with laptop compartment and multiple pockets.',
        price: 89.99,
        originalPrice: 129.99,
        imageUrl: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=500',
        images: [
          'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=500',
        ],
        category: 'Fashion',
        rating: 4.8,
        reviewCount: 234,
        inStock: true,
        brand: 'LeatherCraft',
        specifications: {
          'Material': 'Genuine Leather',
          'Capacity': '25L',
          'Laptop Compartment': 'Up to 15"',
        },
      ),
      Product(
        id: '7',
        name: 'Smart LED Light Bulbs (Pack of 4)',
        description: 'WiFi-enabled smart bulbs with color changing and dimming capabilities.',
        price: 39.99,
        originalPrice: 59.99,
        imageUrl: 'https://images.unsplash.com/photo-1513475382585-d06e58bcb0e0?w=500',
        images: [
          'https://images.unsplash.com/photo-1513475382585-d06e58bcb0e0?w=500',
        ],
        category: 'Home & Kitchen',
        rating: 4.5,
        reviewCount: 678,
        inStock: true,
        brand: 'SmartHome',
        specifications: {
          'Wattage': '9W',
          'Color Range': '16 Million',
          'App Control': 'Yes',
        },
      ),
      Product(
        id: '8',
        name: 'Yoga Mat Premium',
        description: 'Non-slip yoga mat with superior cushioning and eco-friendly materials.',
        price: 34.99,
        originalPrice: 49.99,
        imageUrl: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=500',
        images: [
          'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=500',
        ],
        category: 'Sports & Fitness',
        rating: 4.6,
        reviewCount: 345,
        inStock: true,
        brand: 'ZenFit',
        specifications: {
          'Thickness': '6mm',
          'Material': 'TPE',
          'Size': '72" x 24"',
        },
      ),
      Product(
        id: '9',
        name: 'Ceramic Coffee Maker',
        description: 'Programmable coffee maker with thermal carafe and auto shut-off.',
        price: 79.99,
        originalPrice: 99.99,
        imageUrl: 'https://images.unsplash.com/photo-1517668808823-7113c83e5e54?w=500',
        images: [
          'https://images.unsplash.com/photo-1517668808823-7113c83e5e54?w=500',
        ],
        category: 'Home & Kitchen',
        rating: 4.4,
        reviewCount: 512,
        inStock: true,
        brand: 'BrewMaster',
        specifications: {
          'Capacity': '12 cups',
          'Material': 'Ceramic',
          'Programmable': 'Yes',
        },
      ),
      Product(
        id: '10',
        name: 'Running Shoes Pro',
        description: 'Lightweight running shoes with advanced cushioning and breathable mesh.',
        price: 119.99,
        originalPrice: 149.99,
        imageUrl: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=500',
        images: [
          'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=500',
        ],
        category: 'Sports & Fitness',
        rating: 4.7,
        reviewCount: 923,
        inStock: true,
        brand: 'RunFast',
        specifications: {
          'Weight': '250g',
          'Cushioning': 'Advanced',
          'Breathability': 'High',
        },
      ),
    ];
  }
}

